services:
  postgres-db:
    image: postgres:16-alpine
    container_name: cards_postgres
    environment:
      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: bank_pass
      POSTGRES_DB: cards_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bank_user -d cards_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cards-backend
    # BRAK ports: baza wyłącznie w sieci wewnętrznej (izolacja).
    # Dostęp w dev przez: docker exec -it cards_postgres psql -U bank_user -d cards_db

  card-provider:
    build:
      context: ./card-provider-service
      dockerfile: Dockerfile
    container_name: cards_provider_app
    environment:
      DATABASE_URL: "postgresql+asyncpg://bank_user:bank_pass@postgres-db/cards_db"
      GRPC_PORT: 50051
      VIRTUAL_CARD_ACTIVATION_DELAY: "60"
      PAN_ENCRYPTION_KEY: "karty-platnicze-key-2026"
      CARD_VERIFICATION_KEY: "cvk-secret-key-2026"
      MINIO_ENDPOINT: "minio:9000"
      MINIO_ACCESS_KEY: "minio_admin"
      MINIO_SECRET_KEY: "minio_admin_2026"
      MINIO_BUCKET: "settlements"
      MINIO_RETENTION_DAYS: "1"

      INTERCHANGE_FEE_PERCENT: 1.5
      SCHEME_FEE_PERCENT: 0.3
      ACQUIRER_FEE_PERCENT: 0.2

      SETTLEMENT_INTERVAL_SECONDS: "120" #"86400" jakb bysmy chcieli po dniu a nie po 30 sekundach

      BANK_CAPTURE_URL_POLISH_BANK_A: "http://polish-bank-a:8000"
      BANK_CAPTURE_URL_POLISH_BANK_B: "http://polish-bank-b:8000"

      BANK_CAPTURE_URL_EURO_BANK_A: "http://euro-bank-a:8000"
      BANK_CAPTURE_URL_EURO_BANK_B: "http://euro-bank-b:8000"

      BANK_CAPTURE_URL_UK_BANK_A: "http://uk-bank-a:8000"
      BANK_CAPTURE_URL_UK_BANK_B: "http://uk-bank-b:8000"

      BANK_CAPTURE_URL_US_BANK_A: "http://us-bank-a:8000"
      BANK_CAPTURE_URL_US_BANK_B: "http://us-bank-b:8000"
    depends_on:
      postgres-db:
        condition: service_healthy
      minio:
        condition: service_started
    networks:
      - cards-backend
      - clearing-pl-a
      - clearing-pl-b
      - clearing-eu-a
      - clearing-eu-b
      - clearing-uk-a
      - clearing-uk-b
      - clearing-us-a
      - clearing-us-b

  payment-gateway:
    build:
      context: ./payment-gateway-service
      dockerfile: Dockerfile
    container_name: cards_gateway_app
    ports:
      - "8072:8000"
    volumes:
      - ./payment-gateway-service/data:/app/data    
    environment:
      GRPC_SERVER_URL: "card-provider:50051"
      ADMIN_API_KEY: "admin-secret-key-2026"
      DATABASE_URL: "postgresql+asyncpg://bank_user:bank_pass@postgres-db/cards_db"
    depends_on:
      - card-provider
    networks:
      - cards-frontend
      - cards-backend
      - clearing-pl-a
      - clearing-pl-b
      - clearing-eu-a
      - clearing-eu-b
      - clearing-uk-a
      - clearing-uk-b
      - clearing-us-a
      - clearing-us-b

  admin-panel:
    build:
      context: ./admin-panel
    container_name: cards_admin_panel
    ports:
      - "3072:3000"
    depends_on:
      - payment-gateway
    networks:
      - cards-frontend

  minio:
    image: minio/minio:latest
    container_name: cards_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_admin_2026
    volumes:
      - minio_data:/data
    networks:
      - cards-backend

  wireguard:
    image: linuxserver/wireguard:latest
    container_name: cards_vpn
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    volumes:
      - ./wireguard-config:/config
    ports:
      - "48820:51820/udp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    privileged: true
    networks:
      - cards-frontend
      - cards-backend
    restart: unless-stopped

networks:
  cards-frontend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.137.40.0/24
  cards-backend:
    name: cards-backend
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.137.41.0/24

  clearing-pl-a:
    name: clearing-pl-a-karty
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.137.42.0/24
  clearing-pl-b:
    name: clearing-pl-b-karty
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.137.43.0/24
  clearing-eu-a:
    name: clearing-eu-a-karty
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.137.44.0/24
  clearing-eu-b:
    name: clearing-eu-b-karty
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.137.45.0/24
  clearing-uk-a:
    name: clearing-uk-a-karty
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.137.46.0/24
  clearing-uk-b:
    name: clearing-uk-b-karty
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.137.47.0/24
  clearing-us-a:
    name: clearing-us-a-karty
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.137.48.0/24
  clearing-us-b:
    name: clearing-us-b-karty
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.137.49.0/24

volumes:
  postgres_data:
  minio_data: