# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: card.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'card.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncard.proto\x12\x0c\x63\x61rdprovider\"t\n\x14\x41uthorizationRequest\x12\x12\n\ncard_token\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\x12\x13\n\x0bmerchant_id\x18\x04 \x01(\t\x12\x11\n\tpin_block\x18\x05 \x01(\t\"\xcb\x01\n\x15\x41uthorizationResponse\x12\x1a\n\x12\x61uthorization_code\x18\x01 \x01(\t\x12G\n\rresponse_code\x18\x02 \x01(\x0e\x32\x30.cardprovider.AuthorizationResponse.ResponseCode\x12\x0f\n\x07message\x18\x03 \x01(\t\"<\n\x0cResponseCode\x12\x0c\n\x08\x41PPROVED\x10\x00\x12\x0c\n\x08\x44\x45\x43LINED\x10\x01\x12\x10\n\x0c\x43\x41RD_BLOCKED\x10\x02\"?\n\x11SettlementRequest\x12\x1a\n\x12\x61uthorization_code\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\"=\n\x12SettlementResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0etransaction_id\x18\x02 \x01(\t\"K\n\x11\x43reateCardRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\naccount_id\x18\x02 \x01(\t\x12\x11\n\tcard_type\x18\x03 \x01(\t\"<\n\x12\x43reateCardResponse\x12\x12\n\ncard_token\x18\x01 \x01(\t\x12\x12\n\nmasked_pan\x18\x02 \x01(\t\"$\n\x0eGetCardRequest\x12\x12\n\ncard_token\x18\x01 \x01(\t\".\n\x0b\x43\x61rdDetails\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x02 \x01(\x01\x32\xe2\x02\n\x0c\x43\x61rdProvider\x12_\n\x14\x41uthorizeTransaction\x12\".cardprovider.AuthorizationRequest\x1a#.cardprovider.AuthorizationResponse\x12V\n\x11SettleTransaction\x12\x1f.cardprovider.SettlementRequest\x1a .cardprovider.SettlementResponse\x12O\n\nCreateCard\x12\x1f.cardprovider.CreateCardRequest\x1a .cardprovider.CreateCardResponse\x12H\n\rGetCardStatus\x12\x1c.cardprovider.GetCardRequest\x1a\x19.cardprovider.CardDetailsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'card_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHORIZATIONREQUEST']._serialized_start=28
  _globals['_AUTHORIZATIONREQUEST']._serialized_end=144
  _globals['_AUTHORIZATIONRESPONSE']._serialized_start=147
  _globals['_AUTHORIZATIONRESPONSE']._serialized_end=350
  _globals['_AUTHORIZATIONRESPONSE_RESPONSECODE']._serialized_start=290
  _globals['_AUTHORIZATIONRESPONSE_RESPONSECODE']._serialized_end=350
  _globals['_SETTLEMENTREQUEST']._serialized_start=352
  _globals['_SETTLEMENTREQUEST']._serialized_end=415
  _globals['_SETTLEMENTRESPONSE']._serialized_start=417
  _globals['_SETTLEMENTRESPONSE']._serialized_end=478
  _globals['_CREATECARDREQUEST']._serialized_start=480
  _globals['_CREATECARDREQUEST']._serialized_end=555
  _globals['_CREATECARDRESPONSE']._serialized_start=557
  _globals['_CREATECARDRESPONSE']._serialized_end=617
  _globals['_GETCARDREQUEST']._serialized_start=619
  _globals['_GETCARDREQUEST']._serialized_end=655
  _globals['_CARDDETAILS']._serialized_start=657
  _globals['_CARDDETAILS']._serialized_end=703
  _globals['_CARDPROVIDER']._serialized_start=706
  _globals['_CARDPROVIDER']._serialized_end=1060
# @@protoc_insertion_point(module_scope)
