# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import card_pb2 as card__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in card_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CardProviderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCard = channel.unary_unary(
                '/cardprovider.CardProvider/CreateCard',
                request_serializer=card__pb2.CreateCardRequest.SerializeToString,
                response_deserializer=card__pb2.CreateCardResponse.FromString,
                _registered_method=True)
        self.GetCardStatus = channel.unary_unary(
                '/cardprovider.CardProvider/GetCardStatus',
                request_serializer=card__pb2.GetCardRequest.SerializeToString,
                response_deserializer=card__pb2.CardDetails.FromString,
                _registered_method=True)
        self.BlockCard = channel.unary_unary(
                '/cardprovider.CardProvider/BlockCard',
                request_serializer=card__pb2.BlockCardRequest.SerializeToString,
                response_deserializer=card__pb2.BlockCardResponse.FromString,
                _registered_method=True)
        self.UnblockCard = channel.unary_unary(
                '/cardprovider.CardProvider/UnblockCard',
                request_serializer=card__pb2.UnblockCardRequest.SerializeToString,
                response_deserializer=card__pb2.UnblockCardResponse.FromString,
                _registered_method=True)
        self.AuthorizeTransaction = channel.unary_unary(
                '/cardprovider.CardProvider/AuthorizeTransaction',
                request_serializer=card__pb2.AuthorizationRequest.SerializeToString,
                response_deserializer=card__pb2.AuthorizationResponse.FromString,
                _registered_method=True)
        self.SettleTransaction = channel.unary_unary(
                '/cardprovider.CardProvider/SettleTransaction',
                request_serializer=card__pb2.SettlementRequest.SerializeToString,
                response_deserializer=card__pb2.SettlementResponse.FromString,
                _registered_method=True)
        self.InitiateChargeback = channel.unary_unary(
                '/cardprovider.CardProvider/InitiateChargeback',
                request_serializer=card__pb2.ChargebackRequest.SerializeToString,
                response_deserializer=card__pb2.ChargebackResponse.FromString,
                _registered_method=True)


class CardProviderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateCard(self, request, context):
        """Wydawanie kart
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCardStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BlockCard(self, request, context):
        """Zarządzanie kartą
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnblockCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuthorizeTransaction(self, request, context):
        """Autoryzacja i rozliczenia
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SettleTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitiateChargeback(self, request, context):
        """Chargeback
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CardProviderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCard': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCard,
                    request_deserializer=card__pb2.CreateCardRequest.FromString,
                    response_serializer=card__pb2.CreateCardResponse.SerializeToString,
            ),
            'GetCardStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCardStatus,
                    request_deserializer=card__pb2.GetCardRequest.FromString,
                    response_serializer=card__pb2.CardDetails.SerializeToString,
            ),
            'BlockCard': grpc.unary_unary_rpc_method_handler(
                    servicer.BlockCard,
                    request_deserializer=card__pb2.BlockCardRequest.FromString,
                    response_serializer=card__pb2.BlockCardResponse.SerializeToString,
            ),
            'UnblockCard': grpc.unary_unary_rpc_method_handler(
                    servicer.UnblockCard,
                    request_deserializer=card__pb2.UnblockCardRequest.FromString,
                    response_serializer=card__pb2.UnblockCardResponse.SerializeToString,
            ),
            'AuthorizeTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthorizeTransaction,
                    request_deserializer=card__pb2.AuthorizationRequest.FromString,
                    response_serializer=card__pb2.AuthorizationResponse.SerializeToString,
            ),
            'SettleTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.SettleTransaction,
                    request_deserializer=card__pb2.SettlementRequest.FromString,
                    response_serializer=card__pb2.SettlementResponse.SerializeToString,
            ),
            'InitiateChargeback': grpc.unary_unary_rpc_method_handler(
                    servicer.InitiateChargeback,
                    request_deserializer=card__pb2.ChargebackRequest.FromString,
                    response_serializer=card__pb2.ChargebackResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cardprovider.CardProvider', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cardprovider.CardProvider', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CardProvider(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cardprovider.CardProvider/CreateCard',
            card__pb2.CreateCardRequest.SerializeToString,
            card__pb2.CreateCardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCardStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cardprovider.CardProvider/GetCardStatus',
            card__pb2.GetCardRequest.SerializeToString,
            card__pb2.CardDetails.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BlockCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cardprovider.CardProvider/BlockCard',
            card__pb2.BlockCardRequest.SerializeToString,
            card__pb2.BlockCardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnblockCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cardprovider.CardProvider/UnblockCard',
            card__pb2.UnblockCardRequest.SerializeToString,
            card__pb2.UnblockCardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AuthorizeTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cardprovider.CardProvider/AuthorizeTransaction',
            card__pb2.AuthorizationRequest.SerializeToString,
            card__pb2.AuthorizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SettleTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cardprovider.CardProvider/SettleTransaction',
            card__pb2.SettlementRequest.SerializeToString,
            card__pb2.SettlementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitiateChargeback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cardprovider.CardProvider/InitiateChargeback',
            card__pb2.ChargebackRequest.SerializeToString,
            card__pb2.ChargebackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
